- hosts: all
  become: true
  tasks:
    - name: Ensure dependencies are installed
      apt:
        name:
          - docker.io
          - kubectl
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
